### ISSUE TITLE
 Caffe 0.16 Compilation Error [blocking_queue.cpp] with USE_NCCL:=1 flag.  NCCL v1.3.4-1 

### ISSUE THREAD

**Issue by paninian** [NVIDIA/caffe#402]
### 
I can confirm NCCL 1.3.4 is successfully compiled and has nccl.h file under /usr/local/library/ and 
has other dependend files in /usr/local/lib.
--------------------------------------------------------------------------------------
libnccl-dev/now 1.3.4-1+cuda8.0 amd64 [installed,upgradable to: 2.0.4-1+cuda8.0]
libnccl1/now 1.3.4-1+cuda8.0 amd64 [installed,local]
--------------------------------------------------------------------------------------
Compilation Error
--------------------------------------------------------------------------------------
CXX src/caffe/util/blocking_queue.cpp
In file included from ./include/caffe/parallel.hpp:19:0,
                 from src/caffe/util/blocking_queue.cpp:6:
./include/caffe/util/nccl.hpp:25:16: error: ‘ncclDataType_t’ does not name a type
   static const ncclDataType_t type = ncclFloat;
                ^
./include/caffe/util/nccl.hpp:29:16: error: ‘ncclDataType_t’ does not name a type
   static const ncclDataType_t type = ncclDouble;
                ^
./include/caffe/util/nccl.hpp:34:16: error: ‘ncclDataType_t’ does not name a type
   static const ncclDataType_t type = ncclHalf;
                ^
./include/caffe/util/nccl.hpp:38:8: error: ‘ncclDataType_t’ does not name a type
 inline ncclDataType_t nccl_type(Type type) {
        ^
In file included from src/caffe/util/blocking_queue.cpp:6:0:
./include/caffe/parallel.hpp:79:3: error: ‘ncclUniqueId’ does not name a type
   ncclUniqueId nccl_id_;
   ^
./include/caffe/parallel.hpp:112:3: error: ‘ncclComm_t’ does not name a type
   ncclComm_t nccl_comm_;
   ^
./include/caffe/parallel.hpp:113:3: error: ‘ncclUniqueId’ does not name a type
   ncclUniqueId nccl_id_;
   ^
Makefile:611: recipe for target '.build_release/src/caffe/util/blocking_queue.o' failed
make: *** [.build_release/src/caffe/util/blocking_queue.o] Error 1
--------------------------------------------------------------------------------------

**Comment by paninian** [comment]
We are working on the AWS G3 Large Instance with Tesla M60 - Ubuntu 16.04

**Comment by drnikolaev** [comment]
@paninian 1.3.4 is old, we strongly recommend 2.0.4: https://developer.nvidia.com/nccl
We agree that it must compile with 1.3.4 though and we'll fix it.

**Comment by drnikolaev** [comment]
Hi @paninian I can't reproduce this. Looks like the problem is here:
> I can confirm NCCL 1.3.4 is successfully compiled and has nccl.h file under /usr/local/library/

That header is not supposed to be in `/usr/local/library/`. It should be in `/usr/include`. Please try to install NCCL from `deb` package (better 2.0.4 release). In case you need to build it from sources, try to execute `sudo make install`.
