### PR TITLE
Fix allowing running GPU Caffe on CPU

### LINKED ISSUE #196: Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager
> Hi guys,
> I changed from nvcaffe 015 to nvcaffe016, cuda 7.5 to cuda 8.0, and drivers from 354 to 362 (the one linked with cuda 8.0), cudnn 4 to 5.
> I got a bunch of problems, so I reverted back to nvcaffe 015 (15.7) cuda 7.5, still keeping the 362 driver and the cudnn 5.
> The problem is that I get this strange error when doing classify_one with DIGITS:
> `Error code -6 F0714 21:28:53.351652 15904 gpu_memory.cpp:68] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager`
> the problem happens when I run the classify_one on a training network. It seems like it cannot allocate memory if still used by the training (but plenty of GPU RAM available)
> any idea?
> @engharat https://github.com/NVIDIA/DIGITS/issues/907

### PR DESCRIPTION
**Pull request by drnikolaev**
Fix #196

### CODE REVIEW

**Comment by lukeyeager** [comment]
Oh, I hadn't realized the fix would be just for pycaffe. But it makes sense now and I've verified that it solves #196 (bug 1793197).

LGTM

**Comment by szm-R** [comment]
Hi, does this only works with python? I have nv-caffe 0.15.13 and I'm facing the same problem as #196 when trying to perform inference with a cpp code (everything is fine with the web app, or python). what is the problem? I really don't know what I should do for this!

**Comment by lukeyeager** [comment]
From looking at the changes in the PR, it looks like you need to initialize your GPU memory manager. Something like this:

``` cpp
Caffe::set_mode(Caffe::GPU);
initialize_gpu_memory_scope();
```

**Comment by szm-R** [comment]
I tried but it gives me this error:
error: ‘initialize_gpu_memory_scope’ was not declared in this scope
what should I do?

**Comment by drnikolaev** [comment]
@szm2015 you can grab it [from here](https://github.com/NVIDIA/caffe/blob/caffe-0.15/python/caffe/_caffe.cpp#L55-L68)
