### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mathmanu** [NVIDIA/caffe#397]
I get this compilation after I pulled the code today:

src/caffe/util/math_functions.cu(163): error: identifier "__hfma2" is undefined
src/caffe/util/math_functions.cu(184): error: identifier "__hfma2" is undefined

I am using CUDA 8

Please help. Thanks.

**Comment by drnikolaev** [comment]
@mathmanu is this make or CMake?

**Comment by mathmanu** [comment]
I am using make.

**Comment by drnikolaev** [comment]
Builds fine with CUDA 8.0.86. Could you run `nvcc --version` and paste the output here?

**Comment by mathmanu** [comment]
The output is this:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

Thanks,

**Comment by drnikolaev** [comment]
Ah, got it. Fix is coming soon. Thanks for reporting!

**Comment by drnikolaev** [comment]
@mathmanu , done. Please verify.

**Comment by mathmanu** [comment]
@drnikolaev I just verified that the compilation error is fixed. Thank you.
