### ISSUE TITLE
Top of tree does not compile with cudnn 4.0

### ISSUE THREAD

**Issue by jmancewicz** [NVIDIA/caffe#171]
While compiling (c4d3722 - (4 days ago) Merge pull request #166 from slayton58/thread_pool_parsing - Sergei Nikolaev (origin/caffe-0.15)) with cudnn 4.0.7

I arrive at this error:

`error: ‘cudnnFindConvolutionForwardAlgorithmEx’ was not declared in this scope workspace.size()));`

This commit suddenly looks suspicious.
4248b1f - (2 weeks ago) Use cuDNN routine FindEx to find best algorithm. - Pooya Davoodi

**Comment by lukeyeager** [comment]
Confirmed.

**Comment by lukeyeager** [comment]
If we want to blow up the build matrix even more, we could have TravisCI test this for us:
Code: https://github.com/NVIDIA/caffe/compare/caffe-0.15...lukeyeager:nvidia/travis-cudnn4
Build: https://travis-ci.org/lukeyeager/caffe/builds/138235481

I'm not necessarily saying we should do it, just showing how we could.

**Comment by pooyadavoodi** [comment]
https://github.com/NVIDIA/caffe/pull/174 solves the problem.
