### PR TITLE
[Suggetion] Adding Windows support

### PR DESCRIPTION
**Pull request by Chachay**
Because I'm not from software engineering field, I'm not sure that I'm doing this with a proper manner,
but worked on merging Microsoft caffe HEAD version and NVIDIA caffe 0.15.
- It seems that my version is working with DIGITS 4.0 on windows 10 by now (with CPU) / tested MNIST.
- Building LibCaffe, Caffe and pyCaffe passed on Visual Studio 2013
- DetectNet seems available (this was not available with microsoft Caffe)

The updates from 0.15.8 are
- Copying windows folder from Microsoft Caffe project
- Merging some codes from Microsoft Caffe project
- Modifying some cpp code expression

Thanks.

### CODE REVIEW

**Comment by lunzueta** [comment]
Hi @Chachay. Have you been able to run DetectNet in your Windows machine? I've downloaded your repo, but I couldn't fully compile it. I think there still are many incompatibilities to be solved, like:
- In CPU mode:

`5>  convert_mnist_data.cpp`

`4>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\utility(157): error C2220: warning treated as error - no 'object' file generated`
- In GPU mode without CUDNN:

`bnll_layer.cu(35): error : identifier "::caffe::kBNLL_THRESHOLD" is undefined in device code`
- In GPU mode with CUDNN:

`caffe/util/cudnn.hpp(20): error : declaration is incompatible with "const char *cudnnGetErrorString(cudnnStatus_t)"`
- In both modes: the folder "layers" with files related to DetectNet in the python submodule aren't transferred to the corresponding output folder (which would then be copied to "site-packages").

I'm also trying to make DetectNet work in Windows, but on the other way round, which would be integrating the commits related to DetectNet from NVIDIA's Caffe fork to Microsoft's Caffe fork (here is my ongoing PR for this: https://github.com/Microsoft/caffe/pull/117).

Let's see if we can finally get DetectNet working in Windows...

**Comment by IsaacYangSLA** [comment]
I have a working detectnet in Caffe for Windows [here](https://github.com/isaacyangsla/caffe/tree/windows).  After building it with Visual Studio 2013 (release build), point your DIGITS to $CAFFE_ROOT/build/x64/release and PYTHONPATH to $CAFFE_ROOT/build/x64/release/pycaffe.  It should work in Windows 7 (also tested with GTX 1080).

**Comment by Chachay** [comment]
@lunzueta thank you for your comment. Finally something seems to start :)
Unfortunately I'm at vacation and just after started this work I lost nvidia GPU+Windows environment because of internal job change at work, but still I'd like to see wheter I can contribute something at your PR (if there are something I can!)

At the time, I have been stucked at DetectNet testing due to the lack of GPU environment, at least I could built job in DIGITS though. In CPU mode, I used Python script for MNIST in DIGITS sample folder and I built only minimal libraries to make DIGITS work. 

Now I close this PR because your work will be much quicker than mine.

**Comment by Chachay** [comment]
I needed NVCaffe0.15 on windows again, so I reproduced windows build with some latest libraries. If somebody need a binary please check following.

Chachay/caffe: Caffe: a fast open framework for deep learning. https://github.com/Chachay/caffe/tree/93bf1e9d8f1c0b31b21621cf48a5d42e4530b515
