### ISSUE TITLE
DetectNetTransformationLayerTest failed with opencv 3.1

### ISSUE THREAD

**Issue by mfernezir** [NVIDIA/caffe#263]
I've just installed the latest opencv 3.1 (SHA d1bbc0b6e6c0c5115e54aa6d9f32a1d332a9538c) and the current Caffe (SHA 0bdbb06487d0e458a2bdc8f431f1fd5f35fe91e6).

make runtest had 3 failures regarding DetectNetTransformationLayerTest with the following message:

> OpenCV Error: Assertion failed (!_mv.fixedType() || _mv.empty() || _mv.type() == m.depth()) in split, file /home/developer/opencv/modules/core/src/convert.cpp, line 194
> unknown file: Failure
> C++ exception with description "/home/developer/opencv/modules/core/src/convert.cpp:194: error: (-215) !_mv.fixedType() || _mv.empty() || _mv.type() == m.depth() in function split
> " thrown in the test body.

Additional info: running on Ubuntu 16.04, CUDA 8.0, cuDNN 5.1 and Python 3.5.

**Comment by lukeyeager** [comment]
I bet we haven't supported OpenCV 3.1 since merging https://github.com/NVIDIA/caffe/pull/144.

**Comment by mfernezir** [comment]
In any case, all tests pass if I use v0.15.13.

**Comment by lukeyeager** [comment]
Here are the relevant changes: https://github.com/NVIDIA/caffe/compare/v0.15.13...0bdbb06487d0e458a2bdc8f431f1fd5f35fe91e6

Maybe this was the commit that broke things? https://github.com/NVIDIA/caffe/commit/d47931ad0cb1d5d7dda4f3bf39312faa1f4c8987

I personally am not going to spend any time trying to make this work with OpenCV 3.1. Happy to take a look at a PR if you find a solution.
