### ISSUE TITLE
caffe-0.16 compile error

### ISSUE THREAD

**Issue by renganxu** [NVIDIA/caffe#330]
Hi All,

I downloaded caffe-0.16 branch and tried to compile with cuda 8.0, nccl 1.3.4 and cudnn 6.0. But it has the following error:
NVCC src/caffe/layers/base_data_layer.cu
/usr/include/boost/chrono/duration.hpp(256): error: class "boost::common_type<int_least64_t, int_least64_t, intmax
_t>" has no member "type"
          detected during:
            instantiation of "ToDuration boost::chrono::detail::duration_cast_aux<FromDuration, ToDuration, Period, true, false>::operator()(const FromDuration &) const [with FromDuration=boost::chrono::duration<int_least64_t, boost::nano>, ToDuration=boost::chrono::seconds, Period=boost::ratio<1L, 1000000000L>]" 
(315): here
            instantiation of "ToDuration boost::chrono::detail::duration_cast<FromDuration, ToDuration>::operator()(const FromDuration &) const [with FromDuration=boost::chrono::duration<int_least64_t, boost::nano>, ToDuration=boost::chrono::seconds]" 
(789): here
            instantiation of "boost::enable_if<boost::chrono::detail::is_duration<ToDuration>, ToDuration>::type boost::chrono::duration_cast<ToDuration,Rep,Period>(const boost::chrono::duration<Rep, Period> &) [with ToDuration=boost::chrono::seconds, Rep=int_least64_t, Period=boost::nano]" 
/usr/include/boost/thread/pthread/timespec.hpp(51): here

/usr/include/boost/chrono/duration.hpp(405): error: class "boost::common_type<long, long>" has no member "type"
          detected during instantiation of class "boost::common_type<boost::chrono::duration<Rep1, Period1>, boost::chrono::duration<Rep2, Period2>> [with Rep1=int_least64_t, Period1=boost::nano, Rep2=int_least64_t, Period2=boost::ratio<1L, 1L>]"
/usr/include/boost/thread/pthread/timespec.hpp(52): here

2 errors detected in the compilation of "/tmp/tmpxft_0000477c_00000000-7_base_data_layer.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/layers/base_data_layer.o] Error 1

The boost library version I am using is 1.61.0. Does anyone else have the same error and know the solution? Thanks.

Regards,
Rengan

**Comment by RSly** [comment]
Hi @hfutxrg 
I experienced this before.
The problem was that caffe found the headers in /usr/local/include, but the lib files in /usr/lib and thus it mixed two different boost versions one from /usr and one from /usr/local  

 I reversed the boost ver. to 1.54 and  made sure caffe points to the correct paths and it all worked fine.

**Comment by drnikolaev** [comment]
@hfutxrg @RSly Thank you for reporting this. Reproduced&fixed.

**Comment by renganxu** [comment]
Hi @RSly @drnikolaev,

My boost headers are in /usr/include and the libs are in /usr/lib64, but I still have this issue. I do have boots in other locations, but the boost path in /usr/lib64 has been prepended to LD_LIBRARY_PATH. So it should use the right library. How do I verify the boost path when it is compiled?

I also tried to use cmake since it includes the paths of different libraries when compiling. But in cmake, how do I specify the cudnn library path? (my cudnn path not in CUDA SDK). With Makefile, I was able to do that by adding a CUDNN_ROOT in Makefile.config.

**Comment by drnikolaev** [comment]
Hi @hfutxrg - did you try my fix? 
Simple way to verify where it comes from is to use CMake - it finds everything and prints what and where it was found.

**Comment by renganxu** [comment]
Hi @drnikolaev,

Where your fix is posted? I am trying to use CMake, but as I said, how to specify CUDNN path in cmake?

**Comment by renganxu** [comment]
@drnikolaev I just figured out to set CUDNN path by setting the environment variable CUDNN_DIR. 
Now there is another error about BLAS error. I want to use MKL instead of Atlas. How to change that in CMake?

**Comment by RSly** [comment]
@hfutxrg you can use cmake-gui or ccmake under ubuntu or other cmake interfaces for windows to see all the paths, configurations, etc. 
simply google it for more information

**Comment by drnikolaev** [comment]
@hfutxrg This might be helpful: https://docs.nvidia.com/deeplearning/dgx/caffe-user-guide/index.html
Boost fix: #331

**Comment by renganxu** [comment]
@RSly @drnikolaev Thanks for both of you. I finally installed successfully within singularity container. Probably because my cluster installed boost in many locations and it confused which one to use. But the environment in a container is clean.
